apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  selector:
    matchLabels:
      app: guestbook-ui
  replicas: 2    
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.3
        name: guestbook-ui
        ports:
        - containerPort: 80
